Make merge request guideline more specific
Vanilla-OS/.github pull request #13
Opened 2024-04-16 19:01 UTC by axtloss

This makes the guidelines about merge requests more specific in the way they should be merged, the policy on squashing commits and which commits should be in a MR.

2024-04-16 19:04 UTC, mirkobrombin approved these changes

2024-04-16 19:05 UTC, matbme approved these changes

2024-04-16 20:14 UTC, pietrodicaprio approved these changes

2024-04-16 21:09 UTC, taukakao approved these changes

2024-04-17 00:37 UTC, kbdharun approved these changes
The additions LGTM, just a minor note for Weblate PRs done for non-GUI tools using YAML format, the PRs can't be squashed at Weblate side as the extension only works for Gettext PO files for this I will continue using *GitHub's Squash & Merge option* as manually performing the same using Git on Weblate fork's branch would cause merge conflicts when it tries to rebase future changes.

Rebase would work too but it will clutter the commits log with tens of commits every 2 weeks.

2024-04-17 00:42 UTC, TheEvilSkeleton requested changes

2024-04-17 00:42 UTC, TheEvilSkeleton commented on CONTRIBUTING.md
> +- Once a MR is approved and tested, it should only be merged through the `rebase and merge` feature in GitHub.
```suggestion
- Once a MR is approved and tested, it should only be merged through the "Rebase and merge" feature on GitHub.
```

2024-04-17 00:42 UTC, TheEvilSkeleton commented on CONTRIBUTING.md
> +- If deemed necessary, commits should be squashed in the branch directly through `git`, never through GitHub's `squash and merge`, as that leaves a merge commit behind.
```suggestion
- If deemed necessary, commits should be squashed in the branch directly through `git`, never through GitHub's "Squash and merge", as that leaves a merge commit behind.
```

2024-04-17 04:04 UTC, axtloss commented
> The additions LGTM, just a minor note for Weblate PRs done for non-GUI tools using YAML format, the PRs can't be squashed at Weblate side as the extension only works for Gettext PO files for this I will continue using _GitHub's Squash & Merge option_ as manually performing the same using Git on Weblate fork's branch would cause merge conflicts when it tries to rebase future changes.
> 
> Rebase would work too but it will clutter the commits log with tens of translation update commits every 2 weeks (I.e. see old Apx or ABRoot commit logs).

surely there is a solution to this, like manually squashing commits in the source branch
I dislike the idea of having some special rule just for translations because it does not change the fact that regular merging causes annoying merge commits in the commit log

2024-04-17 04:11 UTC, kbdharun commented
> surely there is a solution to this, like manually squashing commits in the source branch
I dislike the idea of having some special rule just for translations because it does not change the fact that regular merging causes annoying merge commits in the commit log

Manually squashing commits in the source branch is a really bad idea as you would need to force push the changes to the source branch (we wouldn't know which commits were taken into account or dropped) and it will affect all open PRs (that would require manual rebase for the squashing which isn't an easy undertaking with most PRs)

2024-04-17 04:22 UTC, axtloss commented
> Also, we wouldn't know which commits were taken into account or dropped
this does not seem like an issue as GitHub still shows logs before the force commit happened and it being safe to assume that there is no reason for commits to be randomly dropped during manual squashing

> and it will affect all open PRs
how so? unless two PRs modify the same file I don't see why it would conflict

2024-04-17 04:30 UTC, kbdharun commented
> how so? unless two PRs modify the same file I don't see why it would conflict

No, I don't think you are getting the point. What I mean is, that if commits are squashed in the base branch and force pushed, even if the PR doesn't modify any of the files squashed, the GitHub's automated PR check for merging which usually would be like "This branch has no conflicts with the base branch" would show conflicts and you would need to rebase by hand manually all the squashed commits and if you using graphical editors like VSCode then the complexity of the whole process many folds. Without this for every PR we need to depend on people with admin access (i.e. owners) to bypass the check and merge the PR.

2024-04-17 04:34 UTC, axtloss commented
is it possible to make weblate squash the commits itself before making a PR?
also, looking at gnome repos they don't appear to be squashing translations in the first place, which seems like a better idea if specific translations have to be reverted

2024-04-17 04:39 UTC, kbdharun commented
> Is it possible to make weblate squash the commits itself before making a PR? also, looking at gnome repos they don't appear to be squashing translations in the first place, which seems like a better idea if specific translations have to be reverted

Weblate indeed has this feature to Squash the commits per author and language with our current configuration, we could set it to squash all commits but this would mean the author's co-author information would be lost. We could rebase and merge the changes but for every PRs merge, we will have roughly 2-10 commits.

2024-04-17 04:43 UTC, axtloss commented
A good commit history is meant to be properly traceable, which includes having a lot of commits
if translation commits have an according prefix like fix and feat commits do, I don't see any issue with having a lot of them unsquashed

2024-04-17 04:45 UTC, kbdharun commented
> A good commit history is meant to be properly traceable, which includes having a lot of commits if translation commits have an according prefix like fix and feat commits do, I don't see any issue with having a lot of them unsquashed

Noted, will use the "Rebase & Merge" option for these PRs in future.

2024-04-17 12:16 UTC, TheEvilSkeleton approved these changes

2024-04-17 12:44 UTC, merged